### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by CesarStatik** [raisedapp/Hangfire.JobsLogger#23]
It seems that this library is having the same behavior as the "Hangfire.Storage.SQLite.SQLiteMonitoringApi" where you are trying to access keys in the dictionary that are not present. 

HEre is an example:

"error": {
    "code": "ExceptionErrorCode",
    "message": "The given key 'Queue' was not present in the dictionary.",
    "target": "System.Collections.Generic.KeyNotFoundException",
    "details": [
      {
        "code": "ExceptionStacktraceErrorCode",
        "message": "   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Hangfire.JobsLogger.Dashboard.EnqueuedStateRenderer.Render(HtmlHelper helper, IDictionary`2 stateData)\r\n   at Hangfire.Dashboard.Pages.JobDetailsPage.Execute()\r\n   at Hangfire.Dashboard.RazorPage.TransformText(String body)\r\n   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)\r\n   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)\r\n   at Application.Core.AspNetCore.Errors.ErrorHandlerMiddleware.Invoke(HttpContext context, ILogger`1 logger, IHostingEnvironment env)",
        "details": []
      }
    ]
  }
}

**Comment by felixclase** [comment]
Hi,

I have tried to replicate the inconvenience you have several times and it has not happened to me.

Could you share the code you are using?

**Comment by rob893** [comment]
I have this same issue
![image](https://user-images.githubusercontent.com/20483475/108617071-341e8180-73c8-11eb-9401-d281d1e853c8.png)

you can find code using jobs logger here https://github.com/rob893/wow-market-watcher/blob/dev/WoWMarketWatcher.API/BackgroundJobs/PullAuctionData.cs

**Comment by felixclase** [comment]
@rob893, were you able to solve the problem?

In your case what I saw is that you are using beta storage (**Hangfire.Storage.MySql, 2.1.0-beta**)

Try with **Hangfire.Storage.MySql**

![image](https://user-images.githubusercontent.com/1153361/108626327-f6e8dc80-7425-11eb-87e0-cf0889e99aa7.png)

![image](https://user-images.githubusercontent.com/1153361/108626233-85a92980-7425-11eb-9370-38a673d07e6b.png)
![image](https://user-images.githubusercontent.com/1153361/108626238-8d68ce00-7425-11eb-8e0b-1535c68f6de5.png)
![image](https://user-images.githubusercontent.com/1153361/108626255-96599f80-7425-11eb-88f8-61426b99edc5.png)

**Comment by rob893** [comment]
Yep. It was because I was using ILogger wrong and passing the wrong argument for the first argument (jobId) so I deleted my comment because it was user error 🤣 Thanks for the quick response!
