### ISSUE TITLE
Log is always empty

### ISSUE THREAD

**Issue by jfantunes** [raisedapp/Hangfire.JobsLogger#24]
I'm using SeriLog to write logs to a file. So I added this library and append the 

`configuration.UseJobsLogger();`

But no result is displayed in the log tab. I didn't understand if I can't continue to use a external provider like SeriLog and replace it by this or if this can work simultaneously and I'm doing something wrong.

**Comment by felixclase** [comment]
Hi,

They can be used simultaneously, please check the example (Hangfire.JobsLogger.ExampleCore)
