### ISSUE TITLE
The logging is empty

### ISSUE THREAD

**Issue by firionyap10** [raisedapp/Hangfire.JobsLogger#26]
Hi, I am using .Net core and implement this plugin. 
`services.AddHangfire(config =>
{
	config.UseSqlServerStorage(Configuration.GetConnectionString("DefaultConnection")).UseJobsLogger();
	config.UseMediatR();
});`
This is my code in the Startup.cs

`private readonly ILogger<CreateCDR> _logger;

public TestLogging(ILogger<CreateCDR> logger)
{
       _logger = logger
}

public void TestMethod()
{
      context.LogInformation($"{i} - Information Message.. {DateTime.UtcNow.Ticks}");
}`

![image](https://user-images.githubusercontent.com/77774974/105321418-65a60080-5c02-11eb-8420-41acd303808e.png)

this is my code. The logging is empty.
Note: I using Nlog in this project

**Comment by felixclase** [comment]
Hi,

Your method does not have a PerformContext parameter.

Please check the example (Hangfire.JobsLogger.ExampleCore):

![image](https://user-images.githubusercontent.com/1153361/108626471-c0f82800-7426-11eb-9f8c-398f28f80251.png)
